config/routes.rb
Rails.application.routes.draw do
  root 'projects#index'
  devise_for :users
  resources :projects
  resources :comments, only: %i[create destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :project

  validates :text, presence: true
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user

  has_many :comments, dependent: :destroy
  has_many :project_status_histories, dependent: :destroy

  validates :name, :status, presence: true

  before_update :save_status_history

  enum status: %i[backlog developing testing finished]

  private

  def save_status_history
    return unless status_changed?

    ProjectStatusHistory.create(project_id: id, user_id: user.id, status: status)
  end
end

app/models/project_status_history.rb
class ProjectStatusHistory < ApplicationRecord
  belongs_to :project
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :projects
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_project, only: %i[create destroy]

  def create
    Comment.create(comment_params)

    redirect_to project_url(id: @project.id)
  end

  def destroy
    comment = Comment.find(params[:id])
    comment.delete

    redirect_to project_url(id: @project.id)
  end

  private

  def comment_params
    params.permit(:text, :project_id).merge(user_id: current_user.id)
  end

  def set_project
    @project = Project.find(comment_params[:project_id])
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!, except: %i[index]
  before_action :set_project, only: %i[show edit update destroy]

  # GET /projects or /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1 or /projects/1.json
  def show
    @comments = @project.comments
    @status_changes = @project.project_status_histories.order(created_at: :desc)
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit; end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to project_url(@project), notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to project_url(@project), notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_project
    @project = Project.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def project_params
    params.require(:project).permit(:name, :status).merge(user_id: current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project Comments</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if user_signed_in? %>
      <%= link_to 'Logout', destroy_user_session_path, data: { "turbo-method": :delete } %>
    <% else %>
      <%= link_to 'Login', new_user_session_path %>
      <%= link_to 'Create an Account', new_user_registration_path %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/projects/_comments.html.erb
<h2>Comments - <%= @comments.count %></h2>

<% @comments.each do |comment| %>
  <div>
    <%= comment.text %> - <strong><%= comment.user.email %></strong> - <%= time_ago_in_words(comment.created_at) %>
    <% if @project.user == current_user || comment.user == current_user %> 
      <%= link_to :delete , comment_path(id: comment.id, project_id: @project.id), data: { "turbo-method": :delete, turbo_confirm: "Are you sure?" } %>
    <% end %> 
  </div>
  <br>
<% end %>

<%= form_tag(comments_url) do %>
  <div>
    <%= text_field_tag :text, nil, placeholder: 'Comment here...' %>
    <%= hidden_field_tag :project_id, @project.id %>
    <%= submit_tag :comment %>
  </div>
<% end %>
<br>

app/views/projects/_form.html.erb
<%= form_with(model: project) do |form| %>
  <% if project.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :status, style: "display: block" %>
    <%= form.select :status, options_for_select(Project.statuses.map { |key, value| [key.humanize, Project.statuses.key(value)] }, project.status)  %>
  </div>  
  <br>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/_project.html.erb
<div id="<%= dom_id project %>">
  <p>
    <strong>Name:</strong>
    <%= project.name %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= project.status %>
  </p>

  <p>
    <strong>User:</strong>
    <%= project.user.email %>
  </p>

</div>

app/views/projects/_status_changes.html.erb
<h2>Status Changes - <%= @status_changes.count %></h2>

<% @status_changes.each do |change| %>
  <div>
    <%= change.status %> - <%= change.user.email %> - <%= time_ago_in_words(change.created_at) %>
  </div>
  <br>
<% end %>
<br>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render "form", project: @project %>

<br>

<div>
  <%= link_to "Show this project", @project %> |
  <%= link_to "Back to projects", projects_path %>
</div>

app/views/projects/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Projects</h1>

<div id="projects">
  <% @projects.each do |project| %>
    <%= render project %>
    <p>
      <%= link_to "Show this project", project %>
    </p>
  <% end %>
</div>

<%= link_to "New project", new_project_path %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render "form", project: @project %>

<br>

<div>
  <%= link_to "Back to projects", projects_path %>
</div>

app/views/projects/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @project %>
<%= render 'comments' %>
<%= render 'status_changes' %>

<div>
  <% if @project.user == current_user %>
    <%= link_to "Edit this project", edit_project_path(@project) %>
    <%= button_to "Destroy this project", @project, method: :delete %>
  <% end %>
  <br>
  <%= link_to "Back to projects", projects_path %>
</div>